version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mini_agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2536
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8082:8082"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  pgdata:
